name: c2f_img_color
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.10.0
  - pytorch-lightning=1.5.7
  - scikit-image=0.19.0
  - torchvision=0.10.1
  - pip
  - pip:
    - fastai==2.5.3
    - kornia==0.6.2
    - numpy==1.21
    - Pillow==8.4.0
